version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
    ports:
      - 5432:5432

  ruby:
    build: ruby
    volumes:
      - ..:/var/app
      - ./shared_data:/var/shared
      - ./gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
