version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mariadb:
    image: mariadb:10.7 # 10.7 because of https://serverfault.com/questions/1103333/mariadb-10-8-3-in-docker-cant-initialize-timers
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: db2rootpass
      MARIADB_USER: db2user
      MARIADB_PASSWORD: db2pass
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  ruby:
    build: ruby
    volumes:
      - ..:/var/app
      - ~/In-adiutorium:/var/in-adiutorium-sources # TODO extract user-specific path to configuration
      - ./volumes/shared_data:/var/shared
      - ./volumes/gem_cache:/usr/local/bundle/gems
      - ./volumes/pip_cache:/root/.cache/pip
      - ./volumes/python_user_base:/root/.local
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      APP_DATABASE_URL: postgres://postgres:dbpass@db/adiutor_development
      APP_TEST_DATABASE_URL: postgres://postgres:dbpass@db/adiutor_test
      IN_ADIUTORIUM_SOURCES_PATH: /var/in-adiutorium-sources

      PIP_USER: 'true' # make `pip install` install to ~/.local
