version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ruby:
    build: ruby
    volumes:
      - ..:/var/app
      - ~/In-adiutorium:/var/in-adiutorium-sources # TODO extract user-specific path to configuration
      - ./volumes/shared_data:/var/shared
      - ./volumes/gem_cache:/usr/local/bundle/gems
      - ./volumes/pip_cache:/root/.cache/pip
      - ./volumes/python_user_base:/root/.local
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      PIP_USER: 'true' # make `pip install` install to ~/.local
